version: '3.8'

services:
  java_db:
    image: postgres:15-alpine
    container_name: java_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres1.
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  java_app:
    build: .
    image: kosmos-api:latest
    container_name: java_app
    ports:
      - 8080:8080
    environment:
      - HOSPITAL_URL=hospital
      - SQL_DDL=create
      - DB_URL=jdbc:postgresql://java_db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=Postgres1.
      - LOG_LEVEL=INFO
    depends_on:
      - java_db
    



    


  
  